apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/instance: vscode-kfp
    app.kubernetes.io/name: vscode-kfp
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: kubernetes
  name: vscode-kfp
spec:
  params:
    - default: vscode-kfp
      name: APP_NAME
      type: string
    - default: 'https://github.com/alexgroom/vscode-kfp.git'
      name: GIT_REPO
      type: string
    - name: GIT_REVISION
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/alex-fraud-detection/vscode-kfp'
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: DOCKERFILE
          value: Containerfile
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
  workspaces:
    - name: workspace
